name: Runtime image

on:
  push:
    branches: [master, next]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into Github registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/next:${GITHUB_REF#refs/heads/}
          docker build . -f Dockerfile --tag $IMAGE_ID
          docker push $IMAGE_ID

      - name: Extract artifacts
        run: |
          mkdir -p artifacts
          docker run -v $(pwd)/artifacts:/artifacts bergmark/curator/next bash -c 'cp -v /usr/local/bin/* /artifacts'
          bzip2 artifacts/*

      - name: Upload curator executable
        uses: actions/upload-artifact@v1
        with:
          name: curator
          path: artifacts/curator.bz2

      - name: Upload casa-curator executable
        uses: actions/upload-artifact@v1
        with:
          name: casa-curator
          path: artifacts/casa-curator.bz2

      - name: Publish artifacts
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/*
          tag: commit-${{ github.sha }}
          overwrite: true
          file_glob: true
